import type { DetectedProject } from "../../../types/index.js";

/**
 * Generate .claudeignore based on detected project type.
 * Prevents Claude from reading noise files that waste context.
 */
export function generateClaudeignore(detected: DetectedProject): string {
  const sections: string[] = ["# Generated by claude-launchpad"];

  // Universal ignores (every project)
  sections.push(`
# Build output
dist/
build/
out/

# IDE & OS
.vscode/
.idea/
*.swp
*.swo
.DS_Store
Thumbs.db

# Test & coverage
coverage/

# Environment (should never be read)
.env
.env.*
!.env.example`);

  // Language-specific ignores
  const lang = detected.language;

  if (lang === "TypeScript" || lang === "JavaScript") {
    sections.push(`
# Node
node_modules/
.pnp/
.yarn/
.next/
.nuxt/
.output/
.svelte-kit/
.vercel/
.turbo/
pnpm-lock.yaml
package-lock.json
yarn.lock
bun.lockb
.nyc_output/
__snapshots__/`);
  }

  if (lang === "Python") {
    sections.push(`
# Python
__pycache__/
*.pyc
*.pyo
.venv/
venv/
.mypy_cache/
.ruff_cache/
.pytest_cache/
*.egg-info/`);
  }

  if (lang === "Go") {
    sections.push(`
# Go
bin/
vendor/`);
  }

  if (lang === "Rust") {
    sections.push(`
# Rust
target/
Cargo.lock`);
  }

  if (lang === "Ruby") {
    sections.push(`
# Ruby
vendor/bundle/
.bundle/
tmp/
log/`);
  }

  if (lang === "Java" || lang === "Kotlin") {
    sections.push(`
# JVM
target/
build/
.gradle/
*.class
*.jar`);
  }

  if (lang === "Dart") {
    sections.push(`
# Dart/Flutter
.dart_tool/
.packages
build/`);
  }

  if (lang === "PHP") {
    sections.push(`
# PHP
vendor/
composer.lock`);
  }

  if (lang === "C#") {
    sections.push(`
# .NET
bin/
obj/
*.dll`);
  }

  if (lang === "Elixir") {
    sections.push(`
# Elixir
_build/
deps/
.elixir_ls/`);
  }

  if (lang === "Swift") {
    sections.push(`
# Swift
.build/
DerivedData/
*.xcuserdata`);
  }

  return sections.join("\n") + "\n";
}
