import { describe, it, expect } from 'vitest';
import { extractFacts } from '../../../src/commands/memory/services/session-service.js';

// ── extractFacts ─────────────────────────────────────────────

describe('extractFacts', () => {
  it('extracts decision facts', () => {
    const facts = extractFacts('We decided to use SQLite because it requires no external process');
    expect(facts).toHaveLength(1);
    expect(facts[0].type).toBe('semantic');
    expect(facts[0].content).toContain('Decision');
    expect(facts[0].tags).toContain('decision');
  });

  it('extracts bugfix facts', () => {
    const facts = extractFacts('Fixed the FTS5 sync issue by adding triggers');
    expect(facts).toHaveLength(1);
    expect(facts[0].type).toBe('episodic');
    expect(facts[0].tags).toContain('bugfix');
  });

  it('extracts learning facts', () => {
    const facts = extractFacts('Learned that pnpm blocks native module builds');
    expect(facts).toHaveLength(1);
    expect(facts[0].type).toBe('semantic');
    expect(facts[0].tags).toContain('learning');
  });

  it('extracts procedural facts', () => {
    const facts = extractFacts('To rebuild native modules, run npx node-gyp rebuild');
    expect(facts).toHaveLength(1);
    expect(facts[0].type).toBe('procedural');
    expect(facts[0].tags).toContain('howto');
  });

  it('extracts gotcha facts with sufficient length', () => {
    const facts = extractFacts('Gotcha: porter stemmer matches unrelated words causing false positives in search');
    expect(facts).toHaveLength(1);
    expect(facts[0].type).toBe('semantic');
    expect(facts[0].tags).toContain('gotcha');
  });

  it('ignores short gotcha fragments', () => {
    const facts = extractFacts('Gotcha: short thing');
    expect(facts).toHaveLength(0);
  });

  it('ignores gotcha without colon/bang delimiter', () => {
    const facts = extractFacts('There is a caveat to this approach that we should consider carefully');
    expect(facts).toHaveLength(0);
  });

  it('skips system noise lines', () => {
    const transcript = [
      '<system-reminder>some system text</system-reminder>',
      '| column1 | column2 |',
      '```typescript',
      'Caveat: The messages below were generated by the user while running local commands',
    ].join('\n');
    const facts = extractFacts(transcript);
    expect(facts).toHaveLength(0);
  });

  it('handles multiple facts in one transcript', () => {
    const transcript = [
      'Decided to use hybrid search because keyword-only misses semantic matches',
      'Fixed the broken import by adding .js extension',
      'Gotcha: ESM requires explicit file extensions in import paths or Node will fail to resolve',
    ].join('\n');
    const facts = extractFacts(transcript);
    expect(facts).toHaveLength(3);
  });

  it('ignores short lines', () => {
    const facts = extractFacts('ok\nyes\nno');
    expect(facts).toHaveLength(0);
  });

  it('returns empty for empty input', () => {
    const facts = extractFacts('');
    expect(facts).toHaveLength(0);
  });
});
